// Typed client for the ONewPipe server. The shapes mirror the Kotlin DTOs in
// server/src/main/kotlin/fr/arthonetwork/onewpipe/server/Browse.kt and Downloads.kt.
import { localAccountToken } from './account';

export type ItemKind = 'video' | 'channel' | 'playlist';

export interface Item {
  url: string;
  title: string;
  kind: ItemKind;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatarUrl: string;
  thumbnailUrl: string;
  durationText: string;
  durationSeconds: number;
  viewCount: number;
  uploadedText: string;
  subscriberCount: number;
  isLive: boolean;
}

export interface Page {
  items: Item[];
  nextPage?: string | null;
}

export interface Subtitle {
  languageTag: string;
  label: string;
  autoGenerated: boolean;
  mimeType: string;
  url: string;
}

export interface Watch {
  url: string;
  title: string;
  description: string;
  descriptionFormat: 'html' | 'markdown' | 'text';
  uploadedText: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatarUrl: string;
  uploaderSubscriberCount: number;
  uploaderVerified: boolean;
  viewCount: number;
  likeCount: number;
  durationSeconds: number;
  thumbnailUrl: string;
  isLive: boolean;
  tags: string[];
  subtitles: Subtitle[];
  related: Item[];
}

export interface Channel {
  url: string;
  name: string;
  avatarUrl: string;
  bannerUrl: string;
  subscriberCount: number;
  description: string;
  verified: boolean;
  videos: Page;
}

export interface Comment {
  author: string;
  authorAvatarUrl: string;
  text: string;
  likeCount: number;
  publishedText: string;
  pinned: boolean;
  replyCount: number;
}

export interface Comments {
  comments: Comment[];
  nextPage?: string | null;
  disabled: boolean;
}

export interface DownloadOption {
  id: string;
  label: string;
  kind: 'video' | 'audio';
  extension: string;
  sizeBytes: number;
}

export interface DownloadOptions {
  title: string;
  options: DownloadOption[];
}

export type DownloadStatus = 'queued' | 'downloading' | 'muxing' | 'done' | 'failed' | 'cancelled';

export interface DownloadJob {
  id: string;
  url: string;
  title: string;
  fileName: string;
  status: DownloadStatus;
  /** 0..1, or -1 while it cannot be measured. */
  progress: number;
  sizeBytes: number;
  error?: string | null;
  createdAt: number;
}

export type SearchFilter = 'all' | 'videos' | 'channels' | 'playlists';
export type Category = 'all' | 'gaming' | 'music' | 'movies' | 'podcasts';

export class ApiError extends Error {
  readonly status: number;

  constructor(message: string, status: number) {
    super(message);
    this.status = status;
  }
}

async function getJson<T>(path: string, signal?: AbortSignal): Promise<T> {
  return requestJson<T>(path, { signal });
}

/**
 * Downloads use this server's disk, so it asks for the account when the page
 * is not opened on the server's own machine. The token is only sent when the
 * account belongs to this server.
 */
function serverAuthorization(): Record<string, string> {
  const token = localAccountToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

async function requestJson<T>(path: string, init: RequestInit): Promise<T> {
  const response = await fetch(path, init);
  if (!response.ok) {
    let message = `Request failed (${response.status})`;
    try {
      const body = await response.json();
      if (body && typeof body.error === 'string') message = body.error;
    } catch {
      // Not a JSON error body.
    }
    throw new ApiError(message, response.status);
  }
  if (response.status === 204) return undefined as T;
  return response.json() as Promise<T>;
}

const query = (params: Record<string, string | number | undefined>) =>
  Object.entries(params)
    .filter(([, value]) => value !== undefined && value !== '')
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`)
    .join('&');

export const api = {
  trending: (category: Category, signal?: AbortSignal) =>
    getJson<Page>(`/api/v2/trending?${query({ category })}`, signal),
  search: (q: string, filter: SearchFilter, signal?: AbortSignal) =>
    getJson<Page>(`/api/v2/search?${query({ q, filter })}`, signal),
  more: (page: string, signal?: AbortSignal) =>
    getJson<Page>(`/api/v2/more?${query({ page })}`, signal),
  watch: (url: string, signal?: AbortSignal) =>
    getJson<Watch>(`/api/v2/watch?${query({ url })}`, signal),
  channel: (url: string, signal?: AbortSignal) =>
    getJson<Channel>(`/api/v2/channel?${query({ url })}`, signal),
  comments: (url: string, signal?: AbortSignal) =>
    getJson<Comments>(`/api/v2/comments?${query({ url })}`, signal),
  moreComments: (page: string, signal?: AbortSignal) =>
    getJson<Comments>(`/api/v2/comments/more?${query({ page })}`, signal),
  manifestUrl: (url: string) => `/api/manifest?${query({ url })}`,
  downloadOptions: (url: string, signal?: AbortSignal) =>
    getJson<DownloadOptions>(`/api/downloads/options?${query({ url })}`, signal),
  startDownload: (url: string, option: string) =>
    requestJson<DownloadJob>('/api/downloads', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...serverAuthorization() },
      body: JSON.stringify({ url, option })
    }),
  downloads: () => requestJson<DownloadJob[]>('/api/downloads', { headers: serverAuthorization() }),
  download: (id: string) => getJson<DownloadJob>(`/api/downloads/${encodeURIComponent(id)}`),
  cancelDownload: (id: string) => requestJson<void>(`/api/downloads/${encodeURIComponent(id)}`, { method: 'DELETE' }),
  downloadFileUrl: (id: string) => `/api/downloads/${encodeURIComponent(id)}/file`
};

export function formatBytes(bytes: number): string {
  if (bytes < 0) return '';
  if (bytes >= 1024 ** 3) return `${(bytes / 1024 ** 3).toFixed(1)} GB`;
  if (bytes >= 1024 ** 2) return `${(bytes / 1024 ** 2).toFixed(1)} MB`;
  if (bytes >= 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${bytes} B`;
}

export function formatCount(value: number): string {
  if (value < 0) return '';
  if (value >= 1e9) return `${(value / 1e9).toFixed(1).replace(/\.0$/, '')}B`;
  if (value >= 1e6) return `${(value / 1e6).toFixed(1).replace(/\.0$/, '')}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(1).replace(/\.0$/, '')}K`;
  return String(value);
}

export function formatDuration(totalSeconds: number): string {
  const seconds = Math.max(0, Math.floor(totalSeconds));
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const mm = h > 0 ? String(m).padStart(2, '0') : String(m);
  return `${h > 0 ? `${h}:` : ''}${mm}:${String(s).padStart(2, '0')}`;
}
