package fr.arthonetwork.onewpipe.server

import io.ktor.http.HttpStatusCode
import io.ktor.server.response.respond
import io.ktor.server.routing.Route
import io.ktor.server.routing.RoutingContext
import io.ktor.server.routing.get
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import org.schabi.newpipe.extractor.Image
import org.schabi.newpipe.extractor.InfoItem
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.Page
import org.schabi.newpipe.extractor.StreamingService
import org.schabi.newpipe.extractor.channel.ChannelInfo
import org.schabi.newpipe.extractor.channel.ChannelInfoItem
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabInfo
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabs
import org.schabi.newpipe.extractor.comments.CommentsInfo
import org.schabi.newpipe.extractor.comments.CommentsInfoItem
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandler
import org.schabi.newpipe.extractor.linkhandler.SearchQueryHandler
import org.schabi.newpipe.extractor.playlist.PlaylistInfoItem
import org.schabi.newpipe.extractor.search.SearchInfo
import org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeSearchQueryHandlerFactory
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.StreamType
import java.security.SecureRandom
import java.util.concurrent.ConcurrentHashMap

/*
 * API used by the web interface (webapp/): richer DTOs than the original
 * endpoints, pagination through server-side continuation tokens, channels and
 * comments. The original /api/... routes stay unchanged for existing clients.
 */

@Serializable
data class ItemDto(
    val url: String,
    val title: String,
    /** "video", "channel" or "playlist". */
    val kind: String,
    val uploaderName: String = "",
    val uploaderUrl: String = "",
    val uploaderAvatarUrl: String = "",
    val thumbnailUrl: String = "",
    val durationText: String = "",
    val durationSeconds: Long = 0,
    val viewCount: Long = -1,
    val uploadedText: String = "",
    val subscriberCount: Long = -1,
    val isLive: Boolean = false
)

@Serializable
data class PageDto(val items: List<ItemDto>, val nextPage: String? = null)

@Serializable
data class SubtitleDto(
    val languageTag: String,
    val label: String,
    val autoGenerated: Boolean,
    val mimeType: String,
    /** Relayed through /api/stream: the browser cannot fetch YouTube's timed text directly. */
    val url: String
)

@Serializable
data class WatchDto(
    val url: String,
    val title: String,
    val description: String,
    /** "html", "markdown" or "text". */
    val descriptionFormat: String,
    val uploadedText: String,
    val uploaderName: String,
    val uploaderUrl: String,
    val uploaderAvatarUrl: String,
    val uploaderSubscriberCount: Long,
    val uploaderVerified: Boolean,
    val viewCount: Long,
    val likeCount: Long,
    val durationSeconds: Long,
    val thumbnailUrl: String,
    val isLive: Boolean,
    val tags: List<String>,
    val subtitles: List<SubtitleDto>,
    val related: List<ItemDto>
)

@Serializable
data class ChannelDto(
    val url: String,
    val name: String,
    val avatarUrl: String,
    val bannerUrl: String,
    val subscriberCount: Long,
    val description: String,
    val verified: Boolean,
    val videos: PageDto
)

@Serializable
data class CommentDto(
    val author: String,
    val authorAvatarUrl: String,
    val text: String,
    val likeCount: Long,
    val publishedText: String,
    val pinned: Boolean,
    val replyCount: Int
)

@Serializable
data class CommentsDto(
    val comments: List<CommentDto>,
    val nextPage: String? = null,
    val disabled: Boolean = false
)

// ---- Continuations ----------------------------------------------------------

private sealed interface Continuation {
    val expiresAt: Long
}

private data class ChannelContinuation(
    val service: StreamingService,
    val handler: ListLinkHandler,
    val page: Page,
    override val expiresAt: Long
) : Continuation

private data class SearchContinuation(
    val service: StreamingService,
    val handler: SearchQueryHandler,
    val page: Page,
    override val expiresAt: Long
) : Continuation

private data class CommentsContinuation(
    val service: StreamingService,
    val url: String,
    val page: Page,
    override val expiresAt: Long
) : Continuation

private val continuations = ConcurrentHashMap<String, Continuation>()
private const val CONTINUATION_TTL_MS = 60 * 60 * 1000L
private val tokenRandom = SecureRandom()

private fun rememberContinuation(build: (Long) -> Continuation): String {
    val now = System.currentTimeMillis()
    if (continuations.size > 2_000) continuations.entries.removeIf { it.value.expiresAt < now }
    val token = ByteArray(12).also(tokenRandom::nextBytes).joinToString("") { "%02x".format(it) }
    continuations[token] = build(now + CONTINUATION_TTL_MS)
    return token
}

private inline fun <reified T : Continuation> continuation(token: String): T? =
    (continuations[token] as? T)?.takeIf { it.expiresAt > System.currentTimeMillis() }

private fun Page?.validOrNull(): Page? = this?.takeIf { Page.isValid(it) }

// ---- Stream info cache (shared with the DASH manifest) ----------------------

private data class CachedStreamInfo(val info: StreamInfo, val expiresAt: Long)
private val streamInfoCache = ConcurrentHashMap<String, CachedStreamInfo>()
private const val STREAM_INFO_TTL_MS = 5 * 60 * 1000L

/**
 * Opening a video requests its details and its DASH manifest at the same
 * time; both reuse one extraction instead of extracting the video twice.
 */
internal fun cachedStreamInfo(url: String): StreamInfo {
    val now = System.currentTimeMillis()
    streamInfoCache[url]?.takeIf { it.expiresAt > now }?.let { return it.info }
    if (streamInfoCache.size > 200) streamInfoCache.entries.removeIf { it.value.expiresAt < now }
    val service = NewPipe.getServiceByUrl(url) ?: throw IllegalArgumentException("No service found for URL")
    val info = StreamInfo.getInfo(service, url)
    streamInfoCache[url] = CachedStreamInfo(info, now + STREAM_INFO_TTL_MS)
    return info
}

// ---- Mapping ----------------------------------------------------------------

private fun List<Image>?.best(): String =
    this?.maxByOrNull { it.width }?.url ?: this?.firstOrNull()?.url.orEmpty()

internal fun formatDurationText(seconds: Long): String {
    if (seconds <= 0) return ""
    val hours = seconds / 3600
    val minutes = (seconds % 3600) / 60
    val secs = seconds % 60
    return if (hours > 0) {
        "$hours:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}"
    } else {
        "$minutes:${secs.toString().padStart(2, '0')}"
    }
}

internal fun InfoItem.toItemDto(): ItemDto? = when (this) {
    is StreamInfoItem -> ItemDto(
        url = url,
        title = name.orEmpty(),
        kind = "video",
        uploaderName = uploaderName.orEmpty(),
        uploaderUrl = uploaderUrl.orEmpty(),
        uploaderAvatarUrl = uploaderAvatars.best(),
        thumbnailUrl = thumbnails.best(),
        durationText = formatDurationText(duration),
        durationSeconds = duration,
        viewCount = viewCount,
        uploadedText = textualUploadDate.orEmpty(),
        isLive = streamType == StreamType.LIVE_STREAM || streamType == StreamType.AUDIO_LIVE_STREAM
    )
    is ChannelInfoItem -> ItemDto(
        url = url,
        title = name.orEmpty(),
        kind = "channel",
        thumbnailUrl = thumbnails.best(),
        subscriberCount = subscriberCount
    )
    is PlaylistInfoItem -> ItemDto(
        url = url,
        title = name.orEmpty(),
        kind = "playlist",
        uploaderName = uploaderName.orEmpty(),
        thumbnailUrl = thumbnails.best()
    )
    else -> null
}

private fun CommentsInfoItem.toCommentDto() = CommentDto(
    author = uploaderName.orEmpty(),
    authorAvatarUrl = uploaderAvatars.best(),
    text = commentText?.content.orEmpty(),
    likeCount = likeCount.toLong(),
    publishedText = textualUploadDate.orEmpty(),
    pinned = isPinned,
    replyCount = replyCount
)

private fun StreamInfo.toWatchDto(): WatchDto = WatchDto(
    url = url,
    title = name.orEmpty(),
    description = description?.content.orEmpty(),
    // Description is a record whose type is an enum (HTML, MARKDOWN, PLAIN_TEXT).
    descriptionFormat = when (description?.type?.name) {
        "HTML" -> "html"
        "MARKDOWN" -> "markdown"
        else -> "text"
    },
    uploadedText = textualUploadDate.orEmpty(),
    uploaderName = uploaderName.orEmpty(),
    uploaderUrl = uploaderUrl.orEmpty().ifBlank { subChannelUrl.orEmpty() },
    uploaderAvatarUrl = uploaderAvatars.best(),
    uploaderSubscriberCount = uploaderSubscriberCount,
    uploaderVerified = isUploaderVerified,
    viewCount = viewCount,
    likeCount = likeCount,
    durationSeconds = duration,
    thumbnailUrl = thumbnails.best(),
    isLive = streamType == StreamType.LIVE_STREAM || streamType == StreamType.AUDIO_LIVE_STREAM,
    tags = tags.orEmpty(),
    subtitles = subtitles.orEmpty().mapNotNull { subtitle ->
        val source = subtitle.content?.takeIf { subtitle.isUrl && it.isNotBlank() } ?: return@mapNotNull null
        SubtitleDto(
            languageTag = subtitle.languageTag.orEmpty(),
            label = buildString {
                append(subtitle.displayLanguageName ?: subtitle.languageTag.orEmpty())
                if (subtitle.isAutoGenerated) append(" (auto)")
            },
            autoGenerated = subtitle.isAutoGenerated,
            mimeType = subtitle.format?.mimeType ?: "text/vtt",
            url = "/api/stream?t=" + registerRelayTarget(source)
        )
    },
    related = relatedItems.orEmpty().mapNotNull { it.toItemDto() }
)

// ---- Operations (kept outside the routes so they can be tested) -------------

suspend fun watchInfo(url: String): WatchDto = withContext(Dispatchers.IO) {
    cachedStreamInfo(url).toWatchDto()
}

suspend fun searchPage(serviceId: Int, query: String, filter: String): PageDto = withContext(Dispatchers.IO) {
    val service = NewPipe.getService(serviceId)
    val handler = run {
        val youtube = service.searchQHFactory as? YoutubeSearchQueryHandlerFactory
        val contentFilter = when (filter) {
            "videos" -> YoutubeSearchQueryHandlerFactory.VIDEOS
            "channels" -> YoutubeSearchQueryHandlerFactory.CHANNELS
            "playlists" -> YoutubeSearchQueryHandlerFactory.PLAYLISTS
            else -> YoutubeSearchQueryHandlerFactory.ALL
        }
        if (youtube != null) youtube.fromQuery(query, listOf(contentFilter), null)
        else service.searchQHFactory.fromQuery(query)
    }
    val info = SearchInfo.getInfo(service, handler)
    val next = info.nextPage.validOrNull()
    PageDto(
        items = info.relatedItems.mapNotNull { it.toItemDto() }.distinctBy { it.url },
        nextPage = next?.let { page -> rememberContinuation { SearchContinuation(service, handler, page, it) } }
    )
}

suspend fun trendingPage(serviceId: Int, category: String): PageDto =
    PageDto(
        fetchTrending(serviceId, category).map {
            ItemDto(
                url = it.url,
                title = it.title,
                kind = if (it.durationText.isBlank() && it.uploaderName.startsWith("Channel")) "channel" else "video",
                uploaderName = it.uploaderName,
                thumbnailUrl = it.thumbnailUrl,
                durationText = it.durationText,
                viewCount = it.viewCount,
                isLive = it.isLive
            )
        }
    )

suspend fun channelInfo(url: String): ChannelDto = withContext(Dispatchers.IO) {
    val service = NewPipe.getServiceByUrl(url) ?: throw IllegalArgumentException("No service found for URL")
    val channel = ChannelInfo.getInfo(service, url)
    val tab = channel.tabs.firstOrNull { ChannelTabs.VIDEOS in it.contentFilters } ?: channel.tabs.firstOrNull()
    val videos = if (tab == null) {
        PageDto(emptyList())
    } else {
        val tabInfo = ChannelTabInfo.getInfo(service, tab)
        val next = tabInfo.nextPage.validOrNull()
        PageDto(
            items = tabInfo.relatedItems.mapNotNull { it.toItemDto() },
            nextPage = next?.let { page -> rememberContinuation { ChannelContinuation(service, tab, page, it) } }
        )
    }
    ChannelDto(
        url = channel.url ?: url,
        name = channel.name.orEmpty(),
        avatarUrl = channel.avatars.best(),
        bannerUrl = channel.banners.best(),
        subscriberCount = channel.subscriberCount,
        description = channel.description.orEmpty(),
        verified = channel.isVerified,
        videos = videos
    )
}

suspend fun commentsPage(url: String): CommentsDto = withContext(Dispatchers.IO) {
    val service = NewPipe.getServiceByUrl(url) ?: throw IllegalArgumentException("No service found for URL")
    val info = CommentsInfo.getInfo(service, url)
    val next = info.nextPage.validOrNull()
    CommentsDto(
        comments = info.relatedItems.orEmpty().map { it.toCommentDto() },
        nextPage = next?.let { page -> rememberContinuation { CommentsContinuation(service, url, page, it) } },
        disabled = info.isCommentsDisabled
    )
}

/** Next page of a search or a channel. Returns null for unknown or expired tokens. */
suspend fun morePage(token: String): PageDto? = withContext(Dispatchers.IO) {
    continuation<ChannelContinuation>(token)?.let { state ->
        val result = ChannelTabInfo.getMoreItems(state.service, state.handler, state.page)
        continuations.remove(token)
        val next = result.nextPage.validOrNull()
        return@withContext PageDto(
            items = result.items.mapNotNull { it.toItemDto() },
            nextPage = next?.let { page -> rememberContinuation { state.copy(page = page, expiresAt = it) } }
        )
    }
    continuation<SearchContinuation>(token)?.let { state ->
        val result = SearchInfo.getMoreItems(state.service, state.handler, state.page)
        continuations.remove(token)
        val next = result.nextPage.validOrNull()
        return@withContext PageDto(
            items = result.items.mapNotNull { it.toItemDto() },
            nextPage = next?.let { page -> rememberContinuation { state.copy(page = page, expiresAt = it) } }
        )
    }
    null
}

suspend fun moreComments(token: String): CommentsDto? = withContext(Dispatchers.IO) {
    val state = continuation<CommentsContinuation>(token) ?: return@withContext null
    val result = CommentsInfo.getMoreItems(state.service, state.url, state.page)
    continuations.remove(token)
    val next = result.nextPage.validOrNull()
    CommentsDto(
        comments = result.items.map { it.toCommentDto() },
        nextPage = next?.let { page -> rememberContinuation { state.copy(page = page, expiresAt = it) } }
    )
}

// ---- Routes -----------------------------------------------------------------

private suspend fun RoutingContext.requireParameter(name: String): String? {
    val value = call.request.queryParameters[name].orEmpty()
    if (value.isBlank()) {
        call.respond(HttpStatusCode.BadRequest, ErrorResponse("Missing $name"))
        return null
    }
    return value
}

fun Route.browseRoutes() {
    get("/api/v2/watch") {
        val url = requireParameter("url") ?: return@get
        call.respond(watchInfo(url))
    }
    get("/api/v2/search") {
        val query = requireParameter("q") ?: return@get
        val service = call.request.queryParameters["service"]?.toIntOrNull() ?: 0
        call.respond(searchPage(service, query, call.request.queryParameters["filter"] ?: "all"))
    }
    get("/api/v2/trending") {
        val service = call.request.queryParameters["service"]?.toIntOrNull() ?: 0
        call.respond(trendingPage(service, call.request.queryParameters["category"] ?: "all"))
    }
    get("/api/v2/channel") {
        val url = requireParameter("url") ?: return@get
        call.respond(channelInfo(url))
    }
    get("/api/v2/comments") {
        val url = requireParameter("url") ?: return@get
        call.respond(commentsPage(url))
    }
    get("/api/v2/more") {
        val token = requireParameter("page") ?: return@get
        val page = morePage(token)
        if (page == null) call.respond(HttpStatusCode.NotFound, ErrorResponse("Unknown or expired page"))
        else call.respond(page)
    }
    get("/api/v2/comments/more") {
        val token = requireParameter("page") ?: return@get
        val page = moreComments(token)
        if (page == null) call.respond(HttpStatusCode.NotFound, ErrorResponse("Unknown or expired page"))
        else call.respond(page)
    }
}
