package net.newpipe.app.backend

import kotlinx.coroutines.runBlocking
import okhttp3.OkHttpClient
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.localization.Localization
import net.newpipe.app.domain.SearchFilter
import org.schabi.newpipe.extractor.stream.StreamInfo
import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Integration test for the download/stream pipeline.
 *
 * Verifies that a real YouTube video resolves multiple video formats (not just
 * 360p) and that every stream carries a usable content URL. This guards the
 * "downloads only ever show 360p / don't start" regression.
 *
 * Skips (passes) when the network is unavailable, so it is safe in CI.
 */
class StreamInfoTest {

    companion object {
        private val initialized: Boolean by lazy {
            NewPipe.init(
                OkHttpDownloader(OkHttpClient.Builder().build()),
                Localization("en", "US")
            )
            true
        }
    }

    /**
     * A hard-coded video eventually becomes unavailable and turns this test
     * into a silent no-op, so the video under test is picked from live search
     * results instead.
     */
    private fun resolveTestVideo(): StreamInfo? {
        val repository = NewPipeMediaRepository()
        val candidates = runCatching {
            runBlocking { repository.search(0, "music video 4k", SearchFilter.VIDEOS).items }
        }.getOrElse { e ->
            println("SKIP StreamInfoTest (search failed): ${e.message}")
            return null
        }
        candidates.take(5).forEach { candidate ->
            val info = runCatching {
                val service = NewPipe.getServiceByUrl(candidate.url)
                    ?: fail("No service for ${candidate.url}")
                StreamInfo.getInfo(service, candidate.url)
            }.getOrNull()
            if (info != null && (info.videoStreams.orEmpty() + info.videoOnlyStreams.orEmpty()).isNotEmpty()) {
                println("TEST VIDEO: ${info.name} (${candidate.url})")
                return info
            }
        }
        println("SKIP StreamInfoTest: no playable video among the search results")
        return null
    }

    @Test
    fun resolvesMultipleResolutionsWithContentUrls() = runBlocking {
        initialized

        val info = resolveTestVideo() ?: return@runBlocking

        val videos = info.videoStreams ?: emptyList()
        val videoOnly = info.videoOnlyStreams ?: emptyList()
        val audios = info.audioStreams ?: emptyList()

        println("MIXED: ${videos.map { "${it.resolution} (${it.format?.name}) content=${it.content?.take(40)}" }}")
        println("VIDEO-ONLY: ${videoOnly.map { "${it.resolution} (${it.format?.name}) content=${it.content?.take(40)}" }}")
        println("AUDIO: ${audios.map { "${it.averageBitrate}kbps (${it.format?.name}) content=${it.content?.take(40)}" }}")

        // Every subtitle the player offers must carry a usable URL, otherwise
        // the subtitle menu would list entries that play nothing.
        val subtitles = info.subtitles ?: emptyList()
        println("SUBTITLES: ${subtitles.map { "${it.languageTag} (${it.format?.name}) auto=${it.isAutoGenerated}" }}")
        assertTrue(
            subtitles.all { !(it.content ?: it.url).isNullOrBlank() },
            "Every subtitle track should expose a URL"
        )

        val allVideos = videos + videoOnly
        assertTrue(allVideos.isNotEmpty(), "Expected at least one video stream")
        assertTrue(
            allVideos.size >= 2,
            "Expected multiple video formats, got only: ${allVideos.map { it.resolution }}"
        )
        assertTrue(
            allVideos.any { it.resolution.contains("720") || it.resolution.contains("1080") },
            "Expected a resolution above 360p, got: ${allVideos.map { it.resolution }}"
        )
        allVideos.forEach { stream ->
            assertTrue(
                stream.content.isNotBlank(),
                "Video stream ${stream.resolution} has no content URL"
            )
        }
        assertTrue(audios.isNotEmpty(), "Expected at least one audio format")
        audios.forEach { stream ->
            assertTrue(
                stream.content.isNotBlank(),
                "Audio stream has no content URL"
            )
        }
        println(
            "Resolved ${allVideos.size} video formats: " +
                allVideos.map { "${it.resolution} (${it.format?.name})" } +
                " | ${audios.size} audio formats"
        )
    }
}
