/*
 * SPDX-FileCopyrightText: 2024 NewPipe contributors <https://newpipe.net>
 * SPDX-FileCopyrightText: 2026 NewPipe e.V. <https://newpipe-ev.de>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package net.newpipe.app.theme

import androidx.compose.ui.graphics.Color

// Shared ONewPipe brand palette. Keep these values in sync with the web CSS.
val primaryLight = Color(0xFF7C5CFC)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8E1FF)
val onPrimaryContainerLight = Color(0xFF22105A)
val secondaryLight = Color(0xFF247D6B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBCEFE2)
val onSecondaryContainerLight = Color(0xFF052C25)
val tertiaryLight = Color(0xFF34445E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9E4FA)
val onTertiaryContainerLight = Color(0xFF0D1728)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6F7FB)
val onBackgroundLight = Color(0xFF101827)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF101827)
val surfaceVariantLight = Color(0xFFEDF0F7)
val onSurfaceVariantLight = Color(0xFF667085)
val outlineLight = Color(0xFF98A2B3)
val outlineVariantLight = Color(0xFFD9DEEA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF202B3E)
val inverseOnSurfaceLight = Color(0xFFEEF4FF)
val inversePrimaryLight = Color(0xFFB9A9FF)
val surfaceDimLight = Color(0xFFE2E5EC)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F7FB)
val surfaceContainerLight = Color(0xFFEDF0F7)
val surfaceContainerHighLight = Color(0xFFE7EAF1)
val surfaceContainerHighestLight = Color(0xFFDDE2EB)

val primaryDark = Color(0xFFB9A9FF)
val onPrimaryDark = Color(0xFF2B176D)
val primaryContainerDark = Color(0xFF4C3A99)
val onPrimaryContainerDark = Color(0xFFE8E1FF)
val secondaryDark = Color(0xFF50E3C2)
val onSecondaryDark = Color(0xFF052C25)
val secondaryContainerDark = Color(0xFF1B6B5A)
val onSecondaryContainerDark = Color(0xFFBCEFE2)
val tertiaryDark = Color(0xFFB6C7E4)
val onTertiaryDark = Color(0xFF1D2A40)
val tertiaryContainerDark = Color(0xFF34445E)
val onTertiaryContainerDark = Color(0xFFD9E4FA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0D1320)
val onBackgroundDark = Color(0xFFEEF4FF)
val surfaceDark = Color(0xFF151E2E)
val onSurfaceDark = Color(0xFFEEF4FF)
val surfaceVariantDark = Color(0xFF202B3E)
val onSurfaceVariantDark = Color(0xFFAAB6C8)
val outlineDark = Color(0xFF77859D)
val outlineVariantDark = Color(0xFF334158)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEEF4FF)
val inverseOnSurfaceDark = Color(0xFF151E2E)
val inversePrimaryDark = Color(0xFF6248D4)
val surfaceDimDark = Color(0xFF0D1320)
val surfaceBrightDark = Color(0xFF2A374C)
val surfaceContainerLowestDark = Color(0xFF080D16)
val surfaceContainerLowDark = Color(0xFF121A29)
val surfaceContainerDark = Color(0xFF151E2E)
val surfaceContainerHighDark = Color(0xFF1B2638)
val surfaceContainerHighestDark = Color(0xFF202B3E)
